import React, { useEffect, useState } from "react";
import {
  CheckCircle2,
  Download,
  FileCode2,
  LoaderCircle,
  Play,
  RefreshCw,
  SlidersHorizontal,
  Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { audioService } from "@/lib/audioService";

interface LuaPreset {
  name: string;
  description?: string;
  bands?: Array<{
    frequency: number;
    gain: number;
    q: number;
  }>;
  params?: {
    width: number;
    decay: number;
    damping: number;
    mix: number;
  };
}

interface LuaPresetManagerProps {
  className?: string;
  onPresetApplied?: (
    type: "equalizer" | "spatializer",
    preset: LuaPreset,
  ) => void;
}

type Feedback = {
  tone: "success" | "error";
  message: string;
} | null;

export const LuaPresetManager: React.FC<LuaPresetManagerProps> = ({
  className,
  onPresetApplied,
}) => {
  const [equalizerPresets, setEqualizerPresets] = useState<LuaPreset[]>([]);
  const [spatializerPresets, setSpatializerPresets] = useState<LuaPreset[]>([]);
  const [loading, setLoading] = useState(false);
  const [activePresets, setActivePresets] = useState<{
    equalizer: string | null;
    spatializer: string | null;
  }>({ equalizer: null, spatializer: null });
  const [applyingPreset, setApplyingPreset] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<Feedback>(null);

  const loadLuaPresets = async () => {
    setLoading(true);
    setFeedback(null);

    try {
      const [eqPresets, spatialPresets] = await Promise.all([
        audioService.loadLuaPresets("equalizer"),
        audioService.loadLuaPresets("spatializer"),
      ]);

      setEqualizerPresets(eqPresets as LuaPreset[]);
      setSpatializerPresets(spatialPresets as LuaPreset[]);
    } catch {
      setFeedback({
        tone: "error",
        message: "Preset files could not be loaded.",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadLuaPresets();
  }, []);

  const applyPreset = async (
    preset: LuaPreset,
    type: "equalizer" | "spatializer",
  ) => {
    const actionId = `${type}:${preset.name}`;
    setApplyingPreset(actionId);
    setFeedback(null);

    try {
      const success = await audioService.applyLuaPreset(type, preset);
      if (success) {
        setActivePresets((previous) => ({ ...previous, [type]: preset.name }));
        onPresetApplied?.(type, preset);
        setFeedback({
          tone: "success",
          message: `${preset.name} is now active.`,
        });
      } else {
        setFeedback({
          tone: "error",
          message: "Connect audio before applying a preset.",
        });
      }
    } catch {
      setFeedback({
        tone: "error",
        message: `${preset.name} could not be applied.`,
      });
    } finally {
      setApplyingPreset(null);
    }
  };

  const exportPreset = (
    preset: LuaPreset,
    type: "equalizer" | "spatializer",
  ) => {
    let luaContent = "";

    if (type === "equalizer") {
      luaContent = `-- ${preset.name} Equalizer Preset\n`;
      luaContent += "-- Generated by Super Dribble\n\n";
      luaContent += "preset = {\n";
      luaContent += `  name = "${preset.name}",\n`;
      if (preset.description) {
        luaContent += `  description = "${preset.description}",\n`;
      }
      luaContent += "  bands = {\n";
      preset.bands?.forEach((band, index) => {
        luaContent += `    { frequency = ${band.frequency}, gain = ${band.gain}, q = ${band.q} }`;
        if (index < (preset.bands?.length || 0) - 1) luaContent += ",";
        luaContent += "\n";
      });
      luaContent += "  }\n}";
    } else {
      luaContent = `-- ${preset.name} Spatializer Preset\n`;
      luaContent += "-- Generated by Super Dribble\n\n";
      luaContent += "spatial_preset = {\n";
      luaContent += `  name = "${preset.name}",\n`;
      if (preset.description) {
        luaContent += `  description = "${preset.description}",\n`;
      }
      luaContent += "  params = {\n";
      if (preset.params) {
        luaContent += `    width = ${preset.params.width},\n`;
        luaContent += `    decay = ${preset.params.decay},\n`;
        luaContent += `    damping = ${preset.params.damping},\n`;
        luaContent += `    mix = ${preset.params.mix}\n`;
      }
      luaContent += "  }\n}";
    }

    const blob = new Blob([luaContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${preset.name
      .toLowerCase()
      .replace(/\s+/g, "_")}_${type}.lua`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);

    setFeedback({
      tone: "success",
      message: `${preset.name} was exported.`,
    });
  };

  const renderPreset = (
    preset: LuaPreset,
    type: "equalizer" | "spatializer",
  ) => {
    const isActive = activePresets[type] === preset.name;
    const actionId = `${type}:${preset.name}`;
    const isApplying = applyingPreset === actionId;

    return (
      <article key={actionId} className={cn("sd-settings-card", isActive && "is-active")}>
        <div className="flex items-start gap-3">
          <div
            className={cn("sd-settings-icon", type === "spatializer" && "is-spatial")}
          >
            {type === "equalizer" ? (
              <SlidersHorizontal size={17} />
            ) : (
              <Sparkles size={17} />
            )}
          </div>

          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <h4 className="truncate text-[13px] font-semibold text-white">
                {preset.name}
              </h4>
              {isActive && (
                <span className="sd-active-badge">
                  <CheckCircle2 size={11} />
                  Active
                </span>
              )}
            </div>
            {preset.description && (
              <p className="mt-1 text-[12px] leading-relaxed text-white/55">
                {preset.description}
              </p>
            )}
            <p className="data-type mt-2 text-[10px] text-white/40">
              {type === "equalizer"
                ? `${preset.bands?.length ?? 0} bands`
                : `Width ${preset.params?.width ?? 0} · Mix ${preset.params?.mix ?? 0}`}
            </p>
          </div>
        </div>

        <div className="mt-4 flex justify-end gap-2">
          <button
            type="button"
            onClick={() => void applyPreset(preset, type)}
            disabled={Boolean(applyingPreset)}
            aria-label={`Apply ${preset.name}`}
            className="sd-settings-action"
          >
            {isApplying ? (
              <LoaderCircle className="animate-spin" size={14} />
            ) : (
              <Play size={14} fill="currentColor" />
            )}
            Apply
          </button>
          <button
            type="button"
            onClick={() => exportPreset(preset, type)}
            aria-label={`Export ${preset.name}`}
            title="Export Lua preset"
            className="sd-settings-action is-icon"
          >
            <Download size={15} />
          </button>
        </div>
      </article>
    );
  };

  return (
    <div className={cn("space-y-4", className)}>
      <div className="surface-panel flex flex-wrap items-center justify-between gap-3 px-4 py-3.5">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-[11px] bg-[#eef2fb] text-[#667085]">
            <FileCode2 size={17} />
          </div>
          <div>
            <h3 className="text-[13px] font-semibold text-[#343a47]">
              Lua preset files
            </h3>
            <p className="text-[11px] text-[#8b92a1]">
              Loaded from the bundled audio engine
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={() => void loadLuaPresets()}
          disabled={loading}
          className="soft-control flex h-9 items-center gap-2 rounded-[11px] px-3 text-[12px] font-semibold text-[#687084] hover:text-[#3f7df4]"
        >
          {loading ? (
            <LoaderCircle className="animate-spin" size={14} />
          ) : (
            <RefreshCw size={14} />
          )}
          Reload
        </button>
      </div>

      {feedback && (
        <div
          role={feedback.tone === "error" ? "alert" : "status"}
          className={cn(
            "rounded-[14px] border px-4 py-3 text-[12px]",
            feedback.tone === "success"
              ? "border-[#bde6cf] bg-[#f3fcf7] text-[#27784c]"
              : "border-[#efc5cc] bg-[#fff7f8] text-[#a83d4e]",
          )}
        >
          {feedback.message}
        </div>
      )}

      {loading && equalizerPresets.length === 0 ? (
        <div className="surface-panel flex min-h-[240px] items-center justify-center text-[#7f8797]">
          <div className="flex items-center gap-2 text-[13px]">
            <LoaderCircle className="animate-spin" size={18} />
            Loading preset library
          </div>
        </div>
      ) : (
        <div className="grid gap-4 lg:grid-cols-2">
          <section className="surface-panel p-4" aria-labelledby="lua-eq-title">
            <div className="mb-3 flex items-center justify-between">
              <h3
                id="lua-eq-title"
                className="text-[14px] font-semibold text-[#343a47]"
              >
                Equalizer profiles
              </h3>
              <span className="data-type text-[10px] text-[#969daa]">
                {equalizerPresets.length}
              </span>
            </div>
            <div className="space-y-2.5">
              {equalizerPresets.length > 0 ? (
                equalizerPresets.map((preset) =>
                  renderPreset(preset, "equalizer"),
                )
              ) : (
                <p className="rounded-[14px] border border-dashed border-[#dfe3eb] px-4 py-8 text-center text-[12px] text-[#8a91a0]">
                  No equalizer profiles found.
                </p>
              )}
            </div>
          </section>

          <section
            className="surface-panel p-4"
            aria-labelledby="lua-spatial-title"
          >
            <div className="mb-3 flex items-center justify-between">
              <h3
                id="lua-spatial-title"
                className="text-[14px] font-semibold text-[#343a47]"
              >
                Spatial profiles
              </h3>
              <span className="data-type text-[10px] text-[#969daa]">
                {spatializerPresets.length}
              </span>
            </div>
            <div className="space-y-2.5">
              {spatializerPresets.length > 0 ? (
                spatializerPresets.map((preset) =>
                  renderPreset(preset, "spatializer"),
                )
              ) : (
                <p className="rounded-[14px] border border-dashed border-[#dfe3eb] px-4 py-8 text-center text-[12px] text-[#8a91a0]">
                  No spatial profiles found.
                </p>
              )}
            </div>
          </section>
        </div>
      )}
    </div>
  );
};
